### ISSUE TITLE
animations stop on application suspend and resume

### ISSUE THREAD

**Issue by MetaiR** [nativescript-community/ui-lottie#39]
hi,
as I wrote in title, animations are stop after resume app

I tried to solve it with:

```
@Component({
    moduleId: module.id,
    selector: "NoNetPage",
    templateUrl: "./no-net-page.component.html",
    styleUrls: ["./no-net-page.component.scss"],
    providers: [BasicService]
})
export class NoNetPageComponent implements AfterViewInit {
    @ViewChild('wifi') wifi: LottieView;
    constructor(
        private _page: Page,
        private _service: BasicService
    ) {
        const t = this;

        application.on(application.resumeEvent, (args) => {
            const wifi = t.wifi;
            if (wifi !== undefined) {
                wifi.playAnimation();
            }
        });
    }
}
```

but when this runs the application will be crash with this message:
TypeError: t.playAnimation is not a function

btw, I am using nativescript-angular

**Comment by itstheceo** [comment]
I can't speak to the Android side of things but after a brief search regarding lottie-ios it appears to be known behaviour, and in-fact is due to how core animation is handled by iOS itself.

As mentioned [here](https://github.com/airbnb/lottie-ios/issues/413#issuecomment-328163143), if you pause the animation before the app is backgrounded the state will be preserved so you can play again when the app is foregrounded.

You should be able to make use of the [NativeScript application lifecycle events](https://docs.nativescript.org/core-concepts/application-lifecycle#use-application-events) to hopefully achieve the same result.

**Comment by MetaiR** [comment]
@itstheceo 
this problem is also happening in the list view (this time without any application suspending and just with scrolling listview) and if we manually start the animation with list view events, it makes listview very slow
any Idea?

**Comment by itstheceo** [comment]
It sounds like the poor performance that you're experiencing could be due to having many LottieViews instantiated / playing at the same time. How many items are being loaded in the ListView, and how many LottieViews per item?

**Comment by MetaiR** [comment]
there is one animation in each item (they are all the same), and the items number is dynamic because it loads from the server, in my case I think it's about maybe 200 items

**Comment by bradmartin** [comment]
They may not be stopped in the listview even though the items are being recycled. Could be retaining memory. I'd profile it in Android studio and see what is happening personally.

If you want to take more granular control of the items I'd use the onScrollListener of the layout manager of the listview and use the methods to determine items entering/leaving and be sure that lottieviews are being paused and played correctly.

**Comment by MetaiR** [comment]
@bradmartin it cause listview not scrolling smoothly

**Comment by bradmartin** [comment]
Yeah to me that seems to indicate a lot of processing is happening with lottieview instances. If you profile it you can see what's happening.

**Comment by Stanteq** [comment]
Try to bind `loaded` event to your lottie element and start it from there. Because on resume `loaded` event is triggered again.

**Comment by farfromrefug** [comment]
now fixed
