### ISSUE TITLE
code update

### ISSUE THREAD

**Issue by farfromrefug** [nativescript-community/ui-lottie#54]
Hey Brad, 

I migrated your project to the latest version of lottie. Had to modify the swift code a bit.
Now i did that as a fork because i wanted to change the plugin structure like i always do with my plugins.
https://github.com/farfromrefug/nativescript-lottie

let me know if you want a PR

**Comment by bradmartin** [comment]
If all functionality still works or if it's minor changes to be on latest Lottie then definitely 💯👍🔥

**Comment by farfromrefug** [comment]
@bradmartin well feature wise it is more than minor:
* updated to latest api
* added support for json string in src
* support for src from assets folder
* bug fixes and corrections
* complete new repo structure with lerna integration

**Comment by bradmartin** [comment]
all that sounds good to me, IDK much about lerna but assuming the hooks still work for pre-commit stuff then all good to me if you wanna PR it

**Comment by adeyemiadetayoccl** [comment]
how is this going

**Comment by farfromrefug** [comment]
@adeyemiadetayoccl https://github.com/bradmartin/nativescript-lottie/pull/62
