### ISSUE TITLE
Can't play dotlottie (.lottie) files

### ISSUE THREAD

**Issue by emasco7** [nativescript-community/ui-lottie#67]
The nativescript-lottie couldn't play a .lottie file

**Comment by bradmartin** [comment]
Can you link to documentation on `.lottie` files? I'm unfamiliar, possibly it's a new feature that requires an update to the SDKs being used in the plugin.

Thanks.

**Comment by emasco7** [comment]
> Can you link to documentation on `.lottie` files? I'm unfamiliar, possibly it's a new feature that requires an update to the SDKs being used in the plugin.
> 
> Thanks.

[https://dotlottie.io/intro/#prelude](url)

**Comment by bradmartin** [comment]
Looks like Android isn't officially supported https://github.com/dotlottie/player-android so maybe we should wait to provide support when the SDKs are feature complete on the Lottie team side.

**Comment by emasco7** [comment]
> Looks like Android isn't officially supported https://github.com/dotlottie/player-android so maybe we should wait to provide support when the SDKs are feature complete on the Lottie team side.

okay then, we wait

**Comment by farfromrefug** [comment]
This is now possible!
