### ISSUE TITLE
Doesn't autoplay animation when changing the src (on ios)

### ISSUE THREAD

**Issue by lruiz-empyrean** [nativescript-community/ui-lottie#75]
I have a lottie with autoPlay true and after the update to ns7 it stopped working on ios, on android works fine.
It has autoPlay true so it starts on load, but when I change the src to another animation file, the second animation doesn't start. 

This is the code, I'm using Nativescript Vue. 
It should play animation1 -> animation2 -> animation3
data:
```
 data() {
      return {
        src: 'res://animation1.json',
        play: 1
      }
    },
```

template:
`<LottieView
          row="0"
          :src="src"
          loop="false"
          autoPlay="true"
          :completionBlock="onComplete"
          ></LottieView>
`
methods:
```
onComplete(isComplete: boolean): void {

        console.log('oncomplete lottie ', this.src, isComplete)

        if (!isComplete)
          return
        
        if (this.play == 1)
        {
          this.play = 2
          this.src = 'res://animation2.json'
          return
        }

        this.src = 'res://animation3.json'

      }
```

Taking a look at the source, it seems that the lottie.ios.ts file is missing something like this in the srcProperty
(lottie.android.ts has that)
``` 
 if (this.autoPlay) {
        this.playAnimation();
      }
```

**Comment by farfromrefug** [comment]
@lruiz-empyrean should be working now can you confirm?
