### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by kryptus36** [nativescript-community/ui-lottie#92]
This issue is very odd. I posted this to SO a couple days ago, and after many hours of trial and error, I have determined that the following behavior exists when this plugin is installed. When I uninstall it, my nav works normally. I have tried all of the 4.3.x versions with the same result.

If I can help in any way, let me know. Here's the detail..

I have been using the same nav code in my app for a long time, and it suddenly has stopped working in the context of one particular frame.

app-root.xml:
```xml
<Frame id='root-frame' defaultPage="./views/pages/root/root-page"></Frame>
```

root-page.xml snippet
```xml
<sd:RadSideDrawer.mainContent>
  <Frame id="content-frame"></Frame>
</sd:RadSideDrawer.mainContent>
```

In my nav code I have:

```typescript
export function navigate(
  navTarget: string | NavigationEntry,
  otherFrame?: Frame
) {
  const navFrame = otherFrame
    ? otherFrame
    : Frame.getFrameById('content-frame');

  if (typeof navTarget === 'object') {
    console.log('nav ' + navFrame + ' ' + navTarget.moduleName);
    navFrame.navigate(navTarget.moduleName);
    console.log('nav done');
  } else if (typeof navTarget === 'string') {
    console.log('nav ' + navFrame + ' ' + navTarget);
    navFrame.navigate(navTarget);
    console.log('nav done');
  }
}

export function navigateVenue<T>(context: T) {
  const navEntry: NavigationEntry = {
    moduleName: ROUTES.venuePage,
    context,
  };
  navigate(navEntry);
}
```

Then I have a tap handler in home-page.ts:
```typescript
export function onVenueTap(args) {
  const view = <StackLayout>args.object;

  navigateVenue<BPVenue>(view.get('venue'));
}
```

So as you can see, by default I navigate within the content-frame inside my side drawer. But when my tap handler gets called, I get this on the console from my console.log calls:

```
JS: nav Frame<content-frame>@./views/pages/root/root-page.xml:29:7; ./views/pages/venue/venue-page
JS: nav done
```

So you can see, it finds the correct Frame and requested page but the navigation never happens. In my experience this is sometimes because of rendering issues, so I created a blank page:

blank-page.xml
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <Label text='nothing to see' />
  </StackLayout>
</Page>
```

Navigating to that does the same thing.

As a final experiment I tried creating a function:
```typescript
export function navigateBlank(frameId: string) {
  const frame = Frame.getFrameById(frameId);
  navigate(ROUTES.blankPage, frame);
}
```

If I call that with the frameId 'root-frame' it works fine. But calling it with 'content-frame' I get the same output - the navigation function is called but nothing happens to the UI. I also tried renaming 'content-frame' in case there was some conflict. No luck.

**Comment by farfromrefug** [comment]
Hi. There are too many moving part here. To pinpoint the issue you need to recreate it in the simplest way without any other plugin installed.

**Comment by kryptus36** [comment]
I created a repo for it with no plugins.

https://github.com/kryptus36/navtest

If you tap both labels, it works. Install this plugin and retry, and the second one no longer works.

Again, thanks for your time!

**Comment by kryptus36** [comment]
By the way I should mention this is on Android. I have yet to try it on an iDevice.

**Comment by farfromrefug** [comment]
@kryptus36 your issue comes from the fact that this plugin asks for a newer version of androidx appcompat libraries.
You can fix it this way:
* create a file `before-plugins.gradle` in your App_Resources/Android folder
* inside put :
```
ext {
    androidXAppCompat = "1.1.0"
}
```
It should now work.

**Comment by kryptus36** [comment]
@farfromrefug you are my hero!

**Comment by kryptus36** [comment]
This is happening again, despite this file being present.

```
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "16.+"
    androidXAppCompat = "1.1.0"
  }
}
```

@farfromrefug  Can you provide any guidance?

**Comment by farfromrefug** [comment]
you might have added another plugin forcing a newer version. i cant so anything about it

**Comment by kryptus36** [comment]
I hate to be a pain, but if someone can take a look at this for me it would be greatly appreciated.

@farfromrefug this demonstrates it can't be another plugin, unfortunately.

https://github.com/kryptus36/navtest

I have aded the suggested before-plugins.gradle file

This app has 2 frames. If you run it on Android, and tap either of the nav options, it works as expected. 

Now install @nativescript-community/ui-lottie and try again. There's 2 issues:

1. Tappng "Nav in content frame" now simply doesn't work.
2. Tapping "Nav in root frame" works, but when you tap the Android back button, it breaks the layout on the main page.

Uninstall @nativescript-community/ui-lottie and it works again.

**Comment by farfromrefug** [comment]
@kryptus36 you can try 4.4.0. i removed the dependency to appcompat. If it does not fix it i dont know :s

**Comment by kryptus36** [comment]
Unfortunately it's still present :( I've asked for help on discord. Hopefully someone has insight. I really like this plugin and don't want to remove it!

**Comment by farfromrefug** [comment]
@kryptus36 it is weird indeed
i use it in multiple apps without any issue

**Comment by farfromrefug** [comment]
@kryptus36 ok so i ran some test. The issue lies actually within N not being compatible with latest androidx fragment lib.
You can get the same issue without this plugin just by upgrading `@nativescript/android` to to the latest alpha (clean everything!).
nativescript 8.2.0 should fix that though (there is a test version i think , but i am not 100% sure as i use a fork). I am sorry but there is nothing i can do.

**Comment by kryptus36** [comment]
@farfromrefug  no need to apologize you have gone out of your way to help. I will look into testing with N 8.2. Thanks for the hint!

**Comment by kryptus36** [comment]
@farfromrefug much thanks, once again. Using {N} 8.2 alpha on my app as well as the test case app fixes the issue. Closing as it's not a bug in your plugin :) hopefully 8.2 is coming soon!
