### ISSUE TITLE
Maven Dependency download failed (Bintray down?)

### ISSUE THREAD

**Issue by timoschlueter** [nativescript-community/ui-lottie#93]
Hi everyone! Our ci pipeline failed today because of the following error:

```
iew-release.aar
	 + adding aar plugin dependency: /builds/TwAhAv57/0/app/node_modules/nativescript-vibrate/platforms/android/nativescript_vibrate.aar
	 + adding aar plugin dependency: /builds/TwAhAv57/0/app/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
Build file '/builds/TwAhAv57/0/app/platforms/android/app/build.gradle' line: 638
A problem occurred configuring project ':app'.
Could not GET 'http://dl.bintray.com/pixplicity/android/com/airbnb/android/lottie/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
Command ./gradlew failed with exit code 1
```

We are using `"@nativescript-community/ui-lottie": "~4.3.2"` and have no way of fixing this yet.
The Bintray repository has been down in the past but used to be available a few ours later. JFrog announced the shutdown of Bintray a while ago. They changed course and promised to keep the repository online for some time but using Bintray seems very fragile.

Is this even related to this plugin or is the jcenter()/bintray repository configured at some other place in the NativeScript android runtime? I haven't found anything yet.

**Comment by timoschlueter** [comment]
The problem is caused because 4.3.2 of this plugin uses [airbnbs lottie-android](https://github.com/airbnb/lottie-android) dependency in version 4.1+ which internally seems to use bintray.

The solution for our pipeline was adding a `gradle.properties` file in the `App_Resources/Android/` folder with the following content:

```
lottieVersion=4.2.2
```

This forces this plugin (which fortunately evaluates the "lottieVersion"-property before downloading the lottie-android dependency) to download a later version of the dependency which does not seem to use bintray as a repository any more.

This plugin seems to work without any problems with lottie-android 4.2.2. Maybe we should bump the version anyway?

**Comment by farfromrefug** [comment]
@timoschlueter thanks for the report! you are 100% right. Just released a version which fixed this!
Thanks

**Comment by timoschlueter** [comment]
Great! Thank you for the quick response and the fix :)
