### ISSUE TITLE
Build failure with ui-lottie for iOS - Higher minimum deployment target required

### ISSUE THREAD

**Issue by dangrima90** [nativescript-community/ui-lottie#98]
I'm unable to build my NativeScript Vue application due to `ui-lottie`. Currently the application is using version `1.0.0` and this is the error I'm getting:

```bash
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `https://github.com/farfromrefug/lottie-ios.git`)

Specs satisfying the `lottie-ios (from `https://github.com/farfromrefug/lottie-ios.git`)` dependency were found, but they required a higher minimum deployment target.
'pod install' command failed.
```

I tried updating to the latest version `4.4.4`, after which I got the following error:

```bash
[!] CocoaPods could not find compatible versions for pod "dotLottie":
  In Podfile:
    dotLottie (from `https://github.com/farfromrefug/dotlottie-ios.git`, branch `2.0.0`)

Specs satisfying the `dotLottie (from `https://github.com/farfromrefug/dotlottie-ios.git`, branch `2.0.0`)` dependency were found, but they required a higher minimum deployment target.
'pod install' command failed.
```

Application is using NativeScript 7 - at the moment we're in the process of upgrading to NativeScript 8 but still works in progress so I'd like to make it work for NativeScript 7. Is NativeScript 7 an issue?

I've been using the library for over a year and this was never a problem - I've noticed that there were Podfile updates lately, could this be the problem?

**Comment by fernandomeneghetti** [comment]
I'm having the same problem. Any pointers on how to resolve it? I'm already using nativescript 8.

**Comment by dangrima90** [comment]
@fernandomeneghetti As a quick fix for now what I've managed to get it to work by setting the platform version:

```js
// app/App_Resources/iOS/PodFile

platform :ios, '12.0'
```

I'm not sure if this is the way to fix it. Would appreciate any guidance on this.

**Comment by farfromrefug** [comment]
@dangrima90 it appears latest lottie force a higher min sdk :s will make a new minor version which revert to older iOS lib to revert min SDK. then I ll make a major release with the new SDK and 12 min sdk

**Comment by dangrima90** [comment]
@farfromrefug thanks for clarifying what the issue is 👍

**Comment by farfromrefug** [comment]
@dangrima90 @fernandomeneghetti . You can use 4.4.5 to keep old Lottie SDK (iOS) and not bump your iOS min SDK.
If you upgrade 5.0.0 then the min iOS SDK is now 12

**Comment by dangrima90** [comment]
@farfromrefug Many thanks! I can confirm that I've installed version 4.4.5 can successfully built iOS 🚀

**Comment by enich-dev** [comment]
I'm experiencing this issue with the `nativescript-lottie` package. Is there a way to resolve this issue with that package? Things were working up until about a week ago but now there seems to be an issue with `~/node_modules/nativescript-lottie/platforms/ios/Podfile`. We were able to patch this file to use `pod 'lottie-ios', '3.2.3'` rather than `pod 'lottie-ios', :git => 'https://github.com/farfromrefug/lottie-ios.git'` but some of our lotties are displaying and some are not.

**Comment by enich-dev** [comment]
@farfromrefug

**Comment by farfromrefug** [comment]
@enich-dev no there is no way. that plugin is not maintained anymore and replaced by this one

**Comment by enich-dev** [comment]
@farfromrefug I just realized my issue is actually due to something else. Thanks.
